---
printWidth: 110
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
parser: typescript
overrides:
- files: "*.{css,scss}"
  options:
    parser: css
    singleQuote: false
    printWidth: 120
- files: "*.json"
  options:
    parser: json
    printWidth: 100
